# Generated by Django 4.1 on 2022-08-05 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('file', models.FileField(null=True, upload_to='', verbose_name='路径')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=32, unique=True, verbose_name='学号')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('phone', models.CharField(max_length=32, unique=True, verbose_name='电话号码')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='邮箱')),
                ('supervisor', models.CharField(max_length=32, verbose_name='导师')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-register_time'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Sterilizer', '灭菌锅'), ('centrifuge', '离心机'), ('safe', '生物安全柜'), ('incubator', '细胞培养箱'), ('cylinder', '二氧化碳钢瓶'), ('tank', '液氮罐')], max_length=32, verbose_name='设备类型')),
                ('state', models.CharField(max_length=32, verbose_name='仪器状态')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_instruction', to='MainApp.file')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='评论日期')),
                ('text', models.CharField(max_length=4096, verbose_name='评论内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='MainApp.user')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['user', '-date'],
            },
        ),
    ]
