# Generated by Django 4.1 on 2022-08-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['type'], 'verbose_name': '仪器', 'verbose_name_plural': '仪器'},
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=0, max_length=128, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to='C:\\Users\\yanjs\\PycharmProjects\\CellSystem\\download', verbose_name='路径'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='type',
            field=models.CharField(choices=[('Sterilizer', '灭菌锅'), ('centrifuge', '离心机'), ('safe', '生物安全柜'), ('incubator', '细胞培养箱'), ('cylinder', '二氧化碳钢瓶'), ('tank', '液氮罐')], max_length=32, verbose_name='仪器类型'),
        ),
    ]
