# Generated by Django 4.1 on 2022-08-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_instrument_options_user_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='path',
        ),
        migrations.AlterField(
            model_name='instrument',
            name='type',
            field=models.CharField(choices=[('sterilizer', '灭菌锅'), ('centrifuge', '离心机'), ('safe', '生物安全柜'), ('incubator', '细胞培养箱'), ('cylinder', '二氧化碳钢瓶'), ('tank', '液氮罐')], max_length=32, verbose_name='仪器类型'),
        ),
    ]
