# Generated by Django 4.1 on 2022-08-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_rename_file_file_path_alter_instrument_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(null=True, upload_to='./download', verbose_name='路径'),
        ),
    ]
