# Generated by Django 4.1 on 2022-08-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=1024, verbose_name='密码'),
        ),
    ]
