# Generated by Django 4.1 on 2022-08-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='state',
            field=models.CharField(max_length=256, verbose_name='仪器状态'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='type',
            field=models.CharField(choices=[('sterilizer', '灭菌锅'), ('centrifuge', '离心机'), ('safe', '生物安全柜'), ('incubator', '细胞培养箱'), ('cylinder', '二氧化碳钢瓶'), ('tank', '液氮罐')], max_length=256, verbose_name='仪器类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=1024, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=256, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=1024, unique=True, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(max_length=256, unique=True, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='supervisor',
            field=models.CharField(max_length=256, verbose_name='导师'),
        ),
    ]
