# Generated by Django 4.1 on 2022-09-23 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_alter_file_title_alter_instrument_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('taken', '占用'), ('free', '空闲')], max_length=32, verbose_name='状态')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='取/放时间')),
                ('basket', models.DecimalField(decimal_places=0, max_digits=1, verbose_name='篮子编号')),
                ('floor', models.DecimalField(decimal_places=0, max_digits=1, verbose_name='层数编号')),
                ('row', models.DecimalField(decimal_places=0, max_digits=1, verbose_name='行编号')),
                ('column', models.DecimalField(decimal_places=0, max_digits=1, verbose_name='列编号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_user', to='MainApp.user')),
            ],
            options={
                'verbose_name': '液氮罐',
                'verbose_name_plural': '液氮罐',
                'ordering': ['user', '-date'],
            },
        ),
    ]
