# Generated by Django 4.1 on 2022-09-23 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_tankcell'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankCellHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='记录时间')),
                ('tankCell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_cell', to='MainApp.tankcell')),
            ],
            options={
                'verbose_name': '液氮罐操作历史记录',
                'verbose_name_plural': '液氮罐操作历史记录',
                'ordering': ['-date'],
            },
        ),
    ]
