# Generated by Django 4.1 on 2022-09-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_tankcellhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankcell',
            name='name',
            field=models.CharField(default=1, max_length=1024, verbose_name='名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tankcell',
            name='special_attr',
            field=models.CharField(default=1, max_length=1024, verbose_name='特殊属性'),
            preserve_default=False,
        ),
    ]
