# Generated by Django 4.1 on 2022-09-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_tankcell_name_tankcell_special_attr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankcell',
            name='state',
            field=models.CharField(choices=[('占用', 'taken'), ('空闲', 'free')], max_length=32, verbose_name='状态'),
        ),
    ]
