# Generated by Django 4.1 on 2022-09-23 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_alter_tankcell_basket_alter_tankcell_column_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
            ],
            options={
                'verbose_name': '单元组',
                'verbose_name_plural': '单元组',
            },
        ),
        migrations.AlterModelOptions(
            name='tankcellhistory',
            options={'ordering': ['-date', 'tankCell'], 'verbose_name': '液氮罐操作历史记录', 'verbose_name_plural': '液氮罐操作历史记录'},
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('content', models.TextField(verbose_name='内容')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file', to='MainApp.file')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_group', to='MainApp.unitgroup')),
            ],
            options={
                'verbose_name': '单元',
                'verbose_name_plural': '单元',
            },
        ),
    ]
