# Generated by Django 4.1 on 2022-09-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_unitgroup_alter_tankcellhistory_options_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankcell',
            name='basket',
            field=models.DecimalField(decimal_places=0, max_digits=1, verbose_name='篮子编号'),
        ),
        migrations.AlterField(
            model_name='tankcell',
            name='column',
            field=models.DecimalField(decimal_places=0, max_digits=1, verbose_name='列编号'),
        ),
        migrations.AlterField(
            model_name='tankcell',
            name='floor',
            field=models.DecimalField(decimal_places=0, max_digits=1, verbose_name='层数编号'),
        ),
        migrations.AlterField(
            model_name='tankcell',
            name='row',
            field=models.DecimalField(decimal_places=0, max_digits=1, verbose_name='行编号'),
        ),
    ]
