# Generated by Django 3.0.7 on 2022-09-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_alter_tankcell_basket_alter_tankcell_column_and_more'),
        ('MainApp', '0009_auto_20220923_1313'),
    ]

    operations = [
    ]
